# Generated by Django 3.2.18 on 2023-03-21 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m', verbose_name='аватарка')),
                ('coffee_count', models.PositiveIntegerField(default=0, verbose_name='количество попыток сварить кофе')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'информация пользователя',
                'verbose_name_plural': 'информация пользователей',
                'default_related_name': 'profile',
            },
        ),
    ]
