[tool.black]
line-length=79
target-version = ['py39']
skip-string-normalization=true
#exclude=.git,__pycache__,*/migrations/,venv/,ya/manage.py
exclude='''
/(
    \.git
  | __pycache__
  | migrations
  | venv

)/
'''