# Generated by Django 3.2.18 on 2023-03-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('get', 'получено'), ('saw', 'в обработке'), ('ans', 'ответ дан')], default='get', max_length=3, verbose_name='Статус обработки'),
        ),
    ]
