# Generated by Django 3.2.18 on 2023-03-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Когда был написан отзыв', verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(help_text='Максимум 150 символов', max_length=254, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('get', 'получено'), ('saw', 'в обработке'), ('ans', 'ответ дан')], default='get', help_text='Что сейчас происходит с отзывом', max_length=3, verbose_name='статус обработки'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(help_text='Максимальная длина 200 символов', max_length=200, verbose_name='текст'),
        ),
    ]
