# Generated by Django 3.2.18 on 2023-02-21 14:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[\\w-]+$')], verbose_name='Уникальный адрес')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('weight', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32767)])),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[\\w-]+$')], verbose_name='Уникальный адрес')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[\\w-]+$')], verbose_name='Уникальный адрес')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('text', models.TextField(validators=[django.core.validators.RegexValidator('^[A-zА-я0-9 ]*(роскошно|превосходно)[A-zА-я0-9 ]*$')], verbose_name='Описание товара')),
                ('category', models.ForeignKey(blank=True, help_text='Категория, к которой относится товар', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='catalog.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, help_text='Тег для товара', related_name='tags', to='catalog.Tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
    ]
