# Generated by Django 3.2.18 on 2023-02-22 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(validators=[django.core.validators.RegexValidator('(роскошно|превосходно)')], verbose_name='Описание товара'),
        ),
    ]
