# Generated by Django 3.2.18 on 2023-02-23 18:42

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Описание товара обязательно должно содержать слова: роскошно или превосходно', validators=[catalog.validators.ValidateMustContain('роскошно', 'превосходно')], verbose_name='описание товара'),
        ),
    ]
