# Generated by Django 3.2.18 on 2023-02-28 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20230228_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='main_image',
            field=models.ForeignKey(blank=True, help_text='Фото товара', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog.image', verbose_name='Фото'),
        ),
    ]
