# Generated by Django 3.2.18 on 2023-02-28 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_item_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/', verbose_name='Будет приведено к ширине 1280px')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='main_image',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.OneToOneField(blank=True, help_text='Фото товара', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog.mainimage', verbose_name='Фото'),
        ),
    ]
