# Generated by Django 3.2.18 on 2023-02-28 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20230228_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainimage',
            options={'verbose_name': 'главное изображение', 'verbose_name_plural': 'главные изображения'},
        ),
        migrations.AddField(
            model_name='mainimage',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.item', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='mainimage',
            name='image',
            field=models.ImageField(default='', upload_to='media/%Y/%m', verbose_name='Будет приведено к ширине 1280px'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='media/%Y/%m', verbose_name='Будет приведено к ширине 1280px')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.item', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'изображение товара',
                'verbose_name_plural': 'галерея изображений товара',
            },
        ),
    ]
