# Generated by Django 3.2.18 on 2023-02-28 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20230228_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='media/%Y/%m', verbose_name='Будет приведено к ширине 1280px')),
            ],
            options={
                'verbose_name': 'изображение для галереи',
                'verbose_name_plural': 'изображения для галереи',
                'default_related_name': 'gallery',
            },
        ),
        migrations.AlterModelOptions(
            name='mainimage',
            options={'default_related_name': 'main_image', 'verbose_name': 'главное изображение', 'verbose_name_plural': 'главные изображения'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AlterField(
            model_name='mainimage',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='catalog.item', verbose_name='товар'),
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.item', verbose_name='товар'),
        ),
    ]
