# Generated by Django 3.2.18 on 2023-03-01 16:00

import catalog.validators
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20230228_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='Описание товара обязательно должно содержать слова: роскошно или превосходно', validators=[catalog.validators.ValidateMustContain('роскошно', 'превосходно')], verbose_name='описание товара'),
        ),
    ]
