# Generated by Django 3.2.18 on 2023-03-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_item_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(default=False, verbose_name='опубликовано на главной'),
        ),
    ]
