# Generated by Django 3.2.18 on 2023-03-07 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_item_is_on_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='item',
            field=models.ForeignKey(help_text='Наименование товара', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.item', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(default=False, help_text='Включить публикацию на главной', verbose_name='опубликовано на главной'),
        ),
        migrations.AlterField(
            model_name='mainimage',
            name='item',
            field=models.OneToOneField(help_text='Наименование товара', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='catalog.item', verbose_name='товар'),
        ),
    ]
