name: black Lint

on: [push, pull_request]

jobs:
  black-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Black Code Formatter
        uses: lgeiger/black-action@v1.0.1
        args:
          "--check ."